---
name: Checks

on: [push]

jobs:
  test-lint: #define new job called test-lint
    name: Test and Lint
    runs-on: ubuntu-20.04 #the runner on .github
    steps:
      - name: Login to Docker hub #name of the step
        uses: docker/login-action@v1 #pre-made action in .github, action is a docker container and conf for a certain action (login)
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
